serviceInstances:
  saasRegistry:
    parameters:
      xsappname: incident-app
      appName: incident-app
      displayName: incident-app
      description: Sample incident app.
      appUrls:
        getDependencies: "https://<<SubdomainOfProviderSubaccount>>.incident-app.<<SHOOT_DOMAIN>>/callback/v1.0/dependencies"
        # NOTE: this should forward the call to the CAP Operator subscription server
        onSubscription: "https://cap-op.<<SHOOT_DOMAIN>>/provision/tenants/{tenantId}"

  xsuaa:
    parameters:
      xsappname: incident-app

app:
    domains:
        # -- primary domain to expose application routes
        primary: incident-app.<<SHOOT_DOMAIN>>
        additionalDomainRefs: []
    # -- Labels used to identify the istio ingress-gateway component and its corresponding namespace. Ensure that they match the value under
    # -- label section of deployment istio-ingressgateway in the corresponding istio namespace. If not adopt accordingly
    istioIngressGatewayLabels:
        istio: ingressgateway
        app: istio-ingressgateway

btp:
    # -- BTP Global account identifier where the application is hosted
    provider:
        # -- Subdomain of the provider sub-account where application services are created
        subdomain: <<SubdomainOfProviderSubaccount>> # mandatory let helm fail if not provided
        # -- Tenant identifier for the provider sub-account (usually a guid)
        tenantId: <<TenantIdentifierforProviderSubaccount>> # mandatory let helm fail if not provided
    providerSubaccountId: <<ProviderSubaccountId>> # mandatory let helm fail if not provided

imagePullSecrets:
  - regcred

workloads:
  server:
    deploymentDefinition:
      env:
      - name: CDS_ENV
        value: production
      - name: CDS_CONFIG
        value: '{"requires":{"cds.xt.DeploymentService":{"hdi": { "create": {"database_id": "<<HanaInstanceId>>"} }}}}'

  tenantJob:
    jobDefinition:
      env:
      - name: CDS_ENV
        value: production
      - name: CDS_CONFIG
        value: '{"requires":{"cds.xt.DeploymentService":{"hdi": { "create": {"database_id": "<<HanaInstanceId>>"} }}}}'
