@host = http://localhost:4004

#####
#
# ProcessorService
#

### Reading sensitive data (creditCardNo) by default - NOT recommended!
GET {{host}}/odata/v4/processor/Customers
Authorization: Basic alice:wonderland

### Recommendation: Avoid reading sensitive data by explicitly selecting the fields you need
GET {{host}}/odata/v4/processor/Customers?$select=name
Authorization: Basic alice:wonderland

#####
#
# AdminService
#

### Creating a customer with personal data
# @name create_customer
POST {{host}}/odata/v4/admin/Customers
Authorization: Basic alice:wonderland
Content-Type: application/json

{
  "ID": "{{$randomInt 9000000 9999999}}",
  "firstName": "Bob",
  "lastName": "Builder",
  "email": "bob.builder@example.com"
}

### Updating a customer with personal data details
@customer = {{create_customer.response.body.ID}}
PATCH {{host}}/odata/v4/admin/Customers('{{customer}}')
Authorization: Basic alice:wonderland
Content-Type: application/json

{
  "addresses": [
    {
      "city": "Walldorf",
      "postCode": "69190",
      "streetAddress": "Dietmar-Hopp-Allee 16"
    }
  ]
}
