#!/usr/bin/env node
/* eslint-disable no-console */

const cds = require("@sap/cds")
const { read, write, path } = cds.utils
const { promises:fs } = require("fs")
const _stringified = o => JSON.stringify(o,null,2)

const checkout = {

  async 'remote-service' () {
    const xmpls = await read ('xmpls/remote-service/package.json')
    const base = await read ('package.json')
    for (let each of ['API_BUSINESS_PARTNER'])
      base.cds.requires[each] = xmpls.cds.requires[each]
    await write (_stringified(base)).to('package.json')
  },

  async messaging () {
    const xmpls = await read ('xmpls/messaging/package.json')
    const base = await read ('package.json')
    for (let each of ['API_BUSINESS_PARTNER','messaging'])
      base.cds.requires[each] = xmpls.cds.requires[each]
    await write (_stringified(base)).to('package.json')
    await fs.appendFile (path.join(cds.root,'srv','services.cds'), `
      using from './incidents/field'; // Add UI fields for email in annotation
    `)
  }
}

const [,,$1] = process.argv
checkout[$1]?.() || console.log('Usage: ./checkout remote-service | messaging')
